profiles:
    casp2024-edr:
        connector: elastic_ecs
        connection:
            host: localhost
            port: 9200
            selfSignedCert: false
        indices: winlogbeat-8.12.0
        options:
            retrieval_batch_size: 10000
        config:
            auth:
                username: elastic
                password: elastic
    casp2024-netflow:
        connector: elastic_ecs
        connection:
            host: localhost
            port: 9200
            selfSignedCert: false
        indices: filebeat-8.12.2
        options:
            retrieval_batch_size: 10000
        config:
            auth:
                username: elastic
                password: elastic                